apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-clusterA
  version: "1.31"
  region: ap-northeast-2


iamIdentityMappings:
  - arn: arn:aws:iam::950274644703:user/admin
    groups:
      - system:masters
    username: root-admin
    noDuplicateARNs: true

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true

managedNodeGroups:
  - name: app-ng
    labels: { app: nga }
    instanceType: t3.medium
    instanceName: app-node
    desiredCapacity: 2
    minSize: 1
    maxSize: 20
    amiFamily: AmazonLinux2023
    privateNetworking: true
    volumeType: gp2
    volumeEncrypted: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        awsLoadBalancerController: true
        autoScaler: true
