apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <eks name>
  version: "1.32"
  region: ap-northeast-2


iamIdentityMappings:
  - arn: arn:aws:iam::003150130236:user/root
    groups:
      - system:masters
    username: root-admin
    noDuplicateARNs: true

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true

managedNodeGroups:
  - name: <mng name>
    labels: { app: nga }
    instanceType: t3.medium
    instanceName: <node name>
    desiredCapacity: 2
    minSize: 1
    maxSize: 20
    amiFamily: AmazonLinux2023
    privateNetworking: true
    volumeType: gp2
    volumeEncrypted: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        awsLoadBalancerController: true
        autoScaler: true
